title: QMK Firmware
email: hello@qmk.fm
show_downloads: true
description: An open source firmware for AVR and ARM based keyboards
baseurl: ""
url: "https://qmk.fm"
github_username: qmk
repository: qmk/qmk_firmware
collections:
  changes:
    output: true
    permalink: /changes/:name
  tags:
    output: true
    permalink: /tags/:name
  i18n:
    output: true
    permalink: /:path/:name
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: "i18n/zh-cn"
    values:
      lang: "zh-cn"
  -
    scope:
      path: ""
    values:
      layout: qmk