title: QMK Firmware
email: hello@qmk.fm
show_downloads: true
description: QMK Firmware is an open-source keyboard firmware that supports many keyboard projects.
baseurl: ""
url: "http://qmk.fm"
github_username: qmk
repository: qmk/qmk_firmware

theme: jekyll-theme-minimal
gems:
  - jekyll-feed