title: QMK Firmware
email: hello@qmk.fm
show_downloads: true
description: An open source firmware for AVR and ARM based keyboards
baseurl: ""
url: "http://qmk.fm"
github_username: qmk
repository: qmk/qmk_firmware
collections:
  pages:
    output: true
    permalink: /:name
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
  - jekyll-redirect-from